activity:
    resource: "@ActivityBundle/Resources/config/routing.yml"
    prefix:   /activity

esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

friend:
    resource: "@FriendBundle/Resources/config/routing.yml"
    prefix:   /friend

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message
